### PR TITLE
Destroy issues

### LINKED ISSUE #453: Don't destroy bloom when it goes past max size on anvil
I was confused by this behaviour at first and thought it was a bug. It does seem a bit counterintuitive. Would it perhaps be better to just cap the size and refuse to expand it further instead of deleting the bloom entirely?

### LINKED ISSUE #473: Enriched soul soil no longer spawns particles
This is because it checks if the material is FIRE rather than SOUL_FIRE

Should maybe change the particles to something else, but still want some visual distinction from normal soul soil / fire

### LINKED ISSUE #498: Cannot build blocks against bloomery when sneaking

### LINKED ISSUE #506: Sprinkler has wrong range(?)
Image

https://discord.com/channels/1329177304857055273/1453853399635464506/1454756991061983294

### LINKED ISSUE #507: Add countdown in WAILA for core drills

### LINKED ISSUE #509: Dropped items fly in random direction in grindstone, core drills, mixing pot

### LINKED ISSUE #511: Show mixing pot and crucible fluid as an item display instead of using cauldron fluid levels

### LINKED ISSUE #516: Throwing/attacking with research pack uses it

### LINKED ISSUE #533: Crucible processes items even without heat source

### LINKED ISSUE #535: Bronze anvil carries over hammering/working data to other items
Image

### LINKED ISSUE #536: Fallback of ItemTypeWrapper in crucible for blocks

### PR DESCRIPTION
**Pull request by Intybyte**
Fixes #509, fixes #516, fixes #511, fixes #533, fixes #498, fixes #506, fixes #507, fixes #473, fixes #535, fixes #453, fixes #536

### CODE REVIEW

File: src/main/java/io/github/pylonmc/pylon/base/content/machines/fluid/FluidTankEntityDisplayer.java
Comment (LordIdra) [inline src/main/java/io/github/pylonmc/pylon/base/content/machines/fluid/FluidTankEntityDisplayer.java]: May as well go all the way with this and do fluid tanks / portable fluid tanks too

Comment (LordIdra) [reply src/main/java/io/github/pylonmc/pylon/base/content/machines/fluid/FluidTankEntityDisplayer.java]: Yeah sure, just make sure to add a small javadoc to explain what it does. Also happy for this to happen in a different PR

**Review by LordIdra — APPROVED** [review]
Two small things but happy otherwise

File: src/main/java/io/github/pylonmc/pylon/base/util/BaseUtils.java [hunk 1]
```diff
@@ -159,4 +162,34 @@ public boolean shouldBreakBlockUsingTool(@NotNull Block block, @NotNull ItemStac
                 && tool.hasData(DataComponentTypes.TOOL)
                 && tool.hasData(DataComponentTypes.DAMAGE);
     }
+
+    private static final Map<Material, Material> BLOCK_ITEM_FALLBACK = Map.of(
+        Material.FIRE, Material.FLINT_AND_STEEL,
+        Material.SOUL_FIRE, Material.FLINT_AND_STEEL
+    );
+
+    public static ItemStack itemFromKey(NamespacedKey key) {
```
Comment (Seggan) [inline src/main/java/io/github/pylonmc/pylon/base/util/BaseUtils.java]: This needs to document the fallback
