### PR TITLE
Fixes on pit kiln

### LINKED ISSUE #289: Pit Kiln will NOT store the item when player tries to store ONLY 1 item.
https://github.com/user-attachments/assets/16e37501-16f5-4553-a581-f5595f9f3dc5

### PR DESCRIPTION
**Pull request by Intybyte**
Fixes #289, #286

### CODE REVIEW

**Comment by balugaq** [comment]
Haven't tested ingame.

File: src/main/java/io/github/pylonmc/pylon/base/content/machines/smelting/PitKiln.java [hunk 1]
```diff
@@ -53,6 +59,10 @@ public final class PitKiln extends PylonBlock implements
     private static final double MULTIPLIER_DIRT = Settings.get(BaseKeys.PIT_KILN).getOrThrow("item-multipliers.coarse-dirt", ConfigAdapter.DOUBLE);
     private static final double MULTIPLIER_PODZOL = Settings.get(BaseKeys.PIT_KILN).getOrThrow("item-multipliers.podzol", ConfigAdapter.DOUBLE);
 
+    static {
+        Bukkit.getPluginManager().registerEvents(new HopperListener(), PylonBase.getInstance());
```
Comment (LordIdra) [inline src/main/java/io/github/pylonmc/pylon/base/content/machines/smelting/PitKiln.java:63]: This should be done in PylonBase by convention

File: src/main/java/io/github/pylonmc/pylon/base/content/machines/smelting/PitKiln.java [hunk 2]
```diff
@@ -273,6 +290,24 @@ private void tryStartProcessing() {
         }
     }
 
+    // <editor-fold desc="Hopper Listener" defaultstate="collapsed">
+    private static final class HopperListener implements Listener {
```
Comment (LordIdra) [inline src/main/java/io/github/pylonmc/pylon/base/content/machines/smelting/PitKiln.java:294]: I believe we have an interface for this? If not we should - this isn't the kind of thing we'd really want to write a listener for instead of using interfaces

Comment (LordIdra) [reply src/main/java/io/github/pylonmc/pylon/base/content/machines/smelting/PitKiln.java:294]: Maybe PylonContainer

Comment (Intybyte) [reply src/main/java/io/github/pylonmc/pylon/base/content/machines/smelting/PitKiln.java:294]: PylonVanillaContainerBlock filters out all inventory types that are not Container, DecoratedPot isn't a container, so either we nuke the instanceof checks or handle it separately (I  would nuke the Container check in core)

**Review by Seggan — APPROVED** [review]
LGTM other than other comments

**Comment by Intybyte** [comment]
Depends on https://github.com/pylonmc/pylon-core/pull/381
