### PR TITLE
Fix beheading sword dropping killer instead of killed player's head

### LINKED ISSUE #178: Beheading sword drops wrong player head.
example:

`guguguhello` was slain by `tinalness`
in this case, `guguguhello` is dead, and `tinalness` is the killer,
and it drops a `tinalness's head` instead of `guguguhello's head`

### PR DESCRIPTION
**Pull request by OhmV-IR**
Closes #178

### CODE REVIEW

File: src/main/java/io/github/pylonmc/pylon/base/content/combat/BeheadingSword.java [hunk 1]
```diff
@@ -52,10 +52,9 @@ public void onUsedToKillEntity(@NotNull EntityDeathEvent event) {
         ItemStack head;
         if (event.getEntity().getType() == EntityType.PLAYER) {
             // This cast is safe because PylonItemListener only calls this listener when the killer is a player
-            Player killer = ((Player) event.getDamageSource().getCausingEntity());
             head = new ItemStack(Material.PLAYER_HEAD);
             SkullMeta meta = (SkullMeta) head.getItemMeta();
-            meta.setOwningPlayer(killer);
+            meta.setOwningPlayer((Player)event.getEntity());
```
Comment (Seggan) [inline src/main/java/io/github/pylonmc/pylon/base/content/combat/BeheadingSword.java:57]:
```suggestion
            meta.setOwningPlayer((Player) event.getEntity());
```

**Review by Seggan — APPROVED** [review]
