### PR TITLE
Fix health talisman lore

### LINKED ISSUE #848: Incorrect talisman description.
**Issue reported by: agamingdinosaur:**
Simple health talisman says it increases health by 4 ♥️, when in fact it only increases by 2 ♥️ (4 half hearts).

### PR DESCRIPTION
**Pull request by SchnTgaiSpock**
Closes #848

### CODE REVIEW

**Review by balugaq — APPROVED** [review]

File: src/main/java/io/github/pylonmc/pylon/content/talismans/HealthTalisman.java [hunk 1]
```diff
@@ -31,6 +31,6 @@ protected Attribute getAttribute() {
 
     @Override
     public @NotNull List<@NotNull RebarArgument> getPlaceholders() {
-        return List.of(RebarArgument.of("health-boost", UnitFormat.HEARTS.format(attrBonus)));
+        return List.of(RebarArgument.of("health-boost", UnitFormat.HEARTS.format(attrBonus/2)));
```
Comment (OhmV-IR) [inline src/main/java/io/github/pylonmc/pylon/content/talismans/HealthTalisman.java]: can you specify this to use 1 decimal place of precision when attrBonus is odd to avoid floating point error formatting issues

**Review by OhmV-IR — CHANGES_REQUESTED** [review]
almost

**Review by OhmV-IR — APPROVED** [review]
Thanks for the PR
